# Generated by Django 3.2.4 on 2023-05-11 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0002_boleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('rut', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST.producto')),
            ],
        ),
    ]
